version: "3.1"

volumes:
  zookeeper-data:
    driver: local
  zookeeper-log:
    driver: local

services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.5.8
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/data
      - zookeeper-log:/data-log

  kafka:
    container_name: kafka
    build:
      context: kafka/
      args:
        kafka_version: "3.0.0"
        scala_version: "2.13"
    ports:
      - "9092"
    volumes:
      - ${PWD}/kafka/server.properties:/opt/kafka/config/server.properties
    depends_on:
      - zookeeper
